<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>PROJECT DECODE</title>

    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16"/>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="css/footer.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom styles for this template -->
    <link href="css/small-business.css" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131744827-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-131744827-1');
    </script>

    <!-- Facebook Pixel Code -->
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '1995820977131583');
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
                   src="https://www.facebook.com/tr?id=1995820977131583&ev=PageView&noscript=1"
        /></noscript>
    <!-- End Facebook Pixel Code -->
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-1595802385937715",
            enable_page_level_ads: true
        });
    </script>

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/"><img src="vendor/img/brand.png" width="32" height="32" alt=""/></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"/>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item ">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/search"><span style="color: #28a745">Free Code</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/privacy">Privacy Policy</span>
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>


<div class="container">

    <div class="row my-4 ">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    Policy
                </div>
                <div class="card-body text-justify">
                    <p class="text-capitalize text-justify">
                        Hi! My name is Bhavik Mangukiya, I have created and now support this site and I specialize in
                        information security.
                        <br/><br/>
                        Privacy is Protected for This website and copyrights:
                        <br/><br/>
                        This site does not use permanent cookies. However, Google analytics might use them.
                        <br/><br/>
                        This site does not store any IP addresses.
                        <br/><br/>
                        All uploded file is deleted in every 24 hours.
                        <br/><br/>
                        Decompiled files are only visible to you. You can not sharing a direct link to a Java file.
                        Nobody but me has access to this server, and I have more important things to do than to spy on
                        you and also we are not gether any data or colllect the information of user.
                        <br/><br/>
                        Important! Still, if you are working with highly confidential files, consider downloading a
                        decompiler and using it locally.
                        You are not allowed to use this service for any illegal activities.
                        <br/><br/>
                        What We are doing?
                        <br/>
                        My testing includes the following client-side activities:
                        <br/>
                        🤙 Decompilation of the installed app
                        <br/>
                        ✅ Searching for sensitive information hard-coded within the app
                        <br/>
                        ✅ Verifying the security of locally stored credentials
                        <br/>
                        ✅ Checking that SSL certificates and signatures are properly validated
                        <br/>
                        ✅ Discovering insecure use of cryptography for transmitting data or for local storage
                        <br/>
                        ✅ Source code analysis (if appropriate)
                        <br/>
                        ✅ Checking that automatic updates do not provide a conduit for attackers to install arbitrary
                        code
                        <br/>
                        ✅ Verifying all sensitive information is removed after uninstalling the app
                        <br/>
                        ✅ Looking for unintended transmission of data, such as the user’s phonebook when it is not
                        required
                        <br/><br/>

                        The app testing service also includes testing of the web services used by the app. The following
                        aspects are examined in detail to ensure that the backend servers do not expose customer data to
                        other parties:
                        <br/>

                        📝 Server configuration errors
                        <br/>
                        📝 Loopholes in server code or scripts
                        <br/>
                        📝 Advice on data that could have been exposed due to past errors
                        <br/>
                        📝 Testing for known vulnerabilities
                        <br/>
                        📝 Reducing the risk and enticement to attack
                        <br/>
                        📝 Advice on fixes and future security plans
                        <br/>
                        📝 Identify the issues,
                        <br/>
                        📝 Give advice on how to fix them
                        <br/>
                        📝 And control how they are fixed.
                        <br/><br/>

                        Typical issues discovered during a mobile app and server test:
                        <br/>

                        📝 Vulnerability to man-in-the-middle (MITM) attacks
                        <br/>
                        📝 Insecure storage of sensitive data on mobile devices
                        <br/>
                        📝 Insecure use of cryptography
                        <br/>
                        📝 Weak session management
                        <br/>
                        📝 Unauthorised access to other users’ accounts
                        <br/>
                        📝 SQL injection
                        <br/>
                        📝 Server misconfigurations
                        <br/>
                        📝 Command injection
                        <br/>
                        📝 Well-known platform vulnerabilities
                        <br/>
                        📝 Back doors and debug options
                        <br/>
                        📝 Errors triggering sensitive information leaks
                        <br/>
                        📝 Broken ACLs/Weak passwords
                        <br/><br/>
                        if you want to contact me, Email us: apkdecompile@gmail.com
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="row my-4 ">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    CONTACT US
                </div>
                <div class="card-body text-justify">
                    <ul>
                        <li><strong class="text-capitalize">For Request / Query</strong></li>
                        <p>Email Us at : apkdecomplie@gmail.com</p>

                        <li><strong class="text-capitalize">For DMCA / REPORT</strong><span</li>
                        <p>Email Us at : apkdecomplie@gmail.com</p>

                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>


<!--     Footer-->
<footer class="section footer-classic context-dark bg-dark">
    <div class="container">
        <div class="row row-30">
            <div class="col-md-4 col-xl-5">
                <div class="pr-xl-4">
                    &nbsp;
                    <!-- Rights-->
                    <p class="rights"><span>©</span><span class="copyright-year">2018</span>
                        <span>ApkDecompile</span><span>.</span><span>All Rights Reserved.</span>
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                &nbsp;
                <dl class="contact-list">
                    Email: <a href="mailto:#">Apkdecompile@gmail.com</a>
                </dl>
            </div>
            <div class="col-md-4 col-xl-3">
                &nbsp;
                <dl class="contact-list">
                    <a href="/sitemap.xml">Sitemap</a> | &nbsp;
                    <a href="/about">About</a> |&nbsp;
                    <a href="/privacy">Privicy Policy</a>
                </dl>
            </div>
        </div>
    </div>
    <div class="row no-gutters social-container">
        <div class="col">
            <a class="social-inner" href="https://www.facebook.com/bhav.decompile.7"><span
                        class="icon mdi mdi-facebook"></span><span>Facebook</span></a></div>
        <div class="col"><a class="social-inner" href="https://twitter.com/ADecompiler"><span
                        class="icon mdi mdi-twitter"></span><span>twitter</span></a></div>
        <div class="col"><a class="social-inner" href="#"><span
                        class="icon mdi mdi-youtube-play"></span><span>google</span></a></div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>
</html>
