<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Android free Apk - Online Android App source code generater ✅ </title>
    <meta name="description"
          content="We Provide open source <b>Android Free Application</b> & Genetare Code online or Uploca apk file for <b>Apk decompile</b> ">
    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16"/>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom styles for this template -->
    <link href="css/small-business.css" rel="stylesheet">
    <link href="css/footer.css" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131744827-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-131744827-1');
    </script>

    <!-- Facebook Pixel Code -->
    <script>
        !function (f, b, e, v, n, t, s) {
            if (f.fbq) return;
            n = f.fbq = function () {
                n.callMethod ?
                    n.callMethod.apply(n, arguments) : n.queue.push(arguments)
            };
            if (!f._fbq) f._fbq = n;
            n.push = n;
            n.loaded = !0;
            n.version = '2.0';
            n.queue = [];
            t = b.createElement(e);
            t.async = !0;
            t.src = v;
            s = b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t, s)
        }(window, document, 'script',
            'https://connect.facebook.net/en_US/fbevents.js');
        fbq('init', '1995820977131583');
        fbq('track', 'PageView');
    </script>
    <noscript><img height="1" width="1" style="display:none"
                   src="https://www.facebook.com/tr?id=1995820977131583&ev=PageView&noscript=1"
        /></noscript>
    <!-- End Facebook Pixel Code -->
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-1595802385937715",
            enable_page_level_ads: true
        });
    </script>

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/"><img src="vendor/img/brand.png" width="32" height="32" alt=""/></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"/>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="/search"><span style="color: #28a745">Free Code</span>
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/privacy">Privacy Policy</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <div id="inro-dev" class="row my-4">
        <div class="col-lg-7">
            <img class="img-fluid rounded" id="browse" height="700px" src="/vendor/img/tin.png" alt="">
            <input type="file" id="file" accept=".apk" style="display: none;" name="file"/>
        </div>

        <div class="col-lg-5">
            <br/>
            <h4>Resources</h4>
            <p>
                High quality design resources for free. Crafted with love from amazing artists and professional
                designers around the world, ranging from graphic, template , codes & more.
            </p>
        </div>
    </div>

    <!-- Call to Ads Well -->
    <div class="card my-4 text-center">
        <div class="card-body">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- apkdecompile free code 1 -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-1595802385937715"
                 data-ad-slot="3681686372"
                 data-ad-format="auto"
                 data-full-width-responsive="true"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>

    <!-- Content Row -->
    <div class="row">
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-header text-capitalize text-center">
                    ELEMENTS
                </div>
                <div class="card-body ">
                    <li>
                        <strong>SELECT</strong> - Beutiful Ui compunits form the collection ( Icons , App-Ui etc)
                        <a href="#">Find Here!</a>
                    </li>
                </div>
            </div>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <div class="card-header text-capitalize text-center">
                    LIBERARY
                </div>
                <div class="card-body">
                    <li>
                        <strong>USE</strong> - a support liberary for your next feature and app code easy
                        <a href="#">Find Here!</a>
                    </li>
                </div>
            </div>
        </div>
        <!-- /.col-md-4 -->
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-header text-capitalize text-center">
                    CODES
                </div>
                <div class="card-body">
                    <li>
                        <strong>FIND</strong> - some of the features and app already avaliable for free , use them or
                        just add new feature
                        <a href="#">Find Here!</a>
                    </li>
                </div>
            </div>
        </div>
        <!-- /.col-md-4 -->
    </div>


    <!-- Call to Ads Well -->
    <div class="card my-4 text-center">
        <div class="card-body">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- apkdecompile free code 2 -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-1595802385937715"
                 data-ad-slot="2687334751"
                 data-ad-format="auto"
                 data-full-width-responsive="true"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>


    <div class="row my-4 ">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    TOP SEARCHES
                </div>
                <div class="card-body text-justify">
                    <p class="text-capitalize text-justify">
                        Explore what the world is searching.A search term or a topic. search. Or start with an
                        example. keyboard_arrow_down. Or start with an example. HIDE.Here are some of the best of best
                        of the month
                    </p>
                    <p class="text-center text-capitalize font-weight-bold text-info">COMING SOON</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row my-4 ">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    Credits And Licences
                </div>
                <div class="card-body text-justify">
                    <p class="text-capitalize text-justify">
                        In proprietary software, an end-user license agreement (EULA) or software license agreement is
                        the contract between the licensor and user, establishing the user's right to use the
                        software / tools. The license may define ways under which the copy can be used, in addition to
                        the automatic rights of the user including the freedom to use, archive, re-sale, and backup with
                        legal restrictions.
                    </p>
                    <ul>
                        <li><strong class="text-capitalize">Credits</strong></li>
                        <p>COMING SOON</p>
                        <li><strong class="text-capitalize">License</strong></li>
                        <p>COMING SOON</p>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

<!--     Footer-->
<footer class="section footer-classic context-dark bg-dark">
    <div class="container">
        <div class="row row-30">
            <div class="col-md-4 col-xl-5">
                <div class="pr-xl-4">
                    &nbsp;
                    <!-- Rights-->
                    <p class="rights"><span>©</span><span class="copyright-year">2018</span>
                        <span>ApkDecompile</span><span>.</span><span>All Rights Reserved.</span>
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                &nbsp;
                <dl class="contact-list">
                    Email: <a href="mailto:#">Apkdecompile@gmail.com</a>
                </dl>
            </div>
            <div class="col-md-4 col-xl-3">
                &nbsp;
                <dl class="contact-list">
                    <a href="/sitemap.xml">Sitemap</a> | &nbsp;
                    <a href="/about">About</a> |&nbsp;
                    <a href="/privacy">Privicy Policy</a>
                </dl>
            </div>
        </div>
    </div>
    <div class="row no-gutters social-container">
        <div class="col">
            <a class="social-inner" href="https://www.facebook.com/bhav.decompile.7"><span
                        class="icon mdi mdi-facebook"></span><span>Facebook</span></a></div>
        <div class="col"><a class="social-inner" href="https://twitter.com/ADecompiler"><span
                        class="icon mdi mdi-twitter"></span><span>twitter</span></a></div>
        <div class="col"><a class="social-inner" href="#"><span
                        class="icon mdi mdi-youtube-play"></span><span>google</span></a></div>
    </div>
</footer>
<!-- Bootstrap core JavaScript -->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="https://cdn.ywxi.net/js/1.js" async></script>
</html>

