
CREATE TABLE `Worker_Queue` (
  `TIMESTAMPER` timestamp(5) NOT NULL DEFAULT CURRENT_TIMESTAMP(5) ON UPDATE CURRENT_TIMESTAMP(5),
  `UID` varchar(256) NOT NULL,
  `TOOL` varchar(10) NOT NULL,
  `FILENAME` varchar(256) NOT NULL,
  `FILE_BROWSE_LOC` varchar(256) NOT NULL,
  `FILE_DOWNLOAD_URL` varchar(256) NOT NULL,
  `RESULT_DOWNLOAD_URL` varchar(256) NOT NULL,
  `STATUS` varchar(10) NOT NULL,
  `STATUS_MSG` varchar(100) NOT NULL,
  `SYNCED` varchar(10) NOT NULL
) ENGINE=InnoDB;